name: Github Action Group9

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      # Starting deployment
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_CHANNEL: group9
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
          SLACK_ICON: https://avatars.slack-edge.com/2022-03-24/3272769494295_ab7457048ae0deeb52d5_48.png
          SLACK_MESSAGE: "Starting deployment Github-Actions-Group9 :hourglass_flowing_sand: commit: ${{ github.event.head_commit.message }}"
          SLACK_TITLE: Message
          SLACK_USERNAME: Github Bot
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_DEPLOYMENTS }}
      # ******************** X ************************* X ******************

      # Install dependencies
      - name: Install dependencies
        run: yarn install

      # Running test to verify things
      - name: Run test
        run: npm test

      - name: Slack Notification on fail
        uses: rtCamp/action-slack-notify@v2
        if: ${{ failure() }}
        env:
          SLACK_CHANNEL: group9
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
          SLACK_ICON: https://avatars.slack-edge.com/2022-03-24/3272769494295_ab7457048ae0deeb52d5_48.png
          SLACK_MESSAGE: "Failed deployment :x: Github-Actions-Group9: ${{ github.event.head_commit.message }}"
          SLACK_TITLE: Message
          SLACK_USERNAME: Github Bot
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_DEPLOYMENTS }}
  # Applucation deployment
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "github-actions-group9"
          heroku_email: "prakhar.bhardwaj@gogroup.co"
      # Ending deployment
      - name: Slack Notification on fail
        uses: rtCamp/action-slack-notify@v2
        if: ${{ failure() }}
        env:
          SLACK_CHANNEL: group9
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
          SLACK_ICON: https://avatars.slack-edge.com/2022-03-24/3272769494295_ab7457048ae0deeb52d5_48.png
          SLACK_MESSAGE: "Failed deployment :x: Github-Actions-Group9: ${{ github.event.head_commit.message }}"
          SLACK_TITLE: Message
          SLACK_USERNAME: Github Bot
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_DEPLOYMENTS }}
      - name: Slack Notification on success
        uses: rtCamp/action-slack-notify@v2.2.0
        if: ${{ success() }}
        env:
          SLACK_CHANNEL: group9
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
          SLACK_ICON: https://avatars.slack-edge.com/2022-03-24/3272769494295_ab7457048ae0deeb52d5_48.png
          SLACK_MESSAGE: "Success Github-Actions-Group9 :rocket: commit: ${{ github.event.head_commit.message }}"
          SLACK_TITLE: Message
          SLACK_USERNAME: Github Bot
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_DEPLOYMENTS }}
